/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.5.22 : Database - resturant
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`resturant` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `resturant`;

/* Function  structure for function  `CHECK_QUANTITY_AVILABILITY` */

/*!50003 DROP FUNCTION IF EXISTS `CHECK_QUANTITY_AVILABILITY` */;
DELIMITER $$

/*!50003 CREATE DEFINER=`root`@`localhost` FUNCTION `CHECK_QUANTITY_AVILABILITY`( FN_I_ITEM_NAME CHAR(30), ITEM_QUANTITY INT) RETURNS tinyint(1)
BEGIN
declare QUANTITY_AVILABLE_FLAG BOOLEAN;
declare QUANTY_LEFT int;
 SELECT FOOD_CATEGORY_ID INTO @V_CATEGORY_ID FROM ITEMS_CATEGORY 
WHERE FOOD_ITEM_ID=(SELECT ID FROM FOOD_ITEMS WHERE ITEM=FN_I_ITEM_NAME) AND FOOD_CATEGORY_ID IN 
(SELECT ID FROM FOOD_SCHEDULE WHERE CURTIME() BETWEEN TIME_START AND TIME_END);
  ( SELECT QUANTITY_REMAINING INTO QUANTY_LEFT FROM stock_available WHERE FOOD_TYPE=(SELECT FOOD_TYPE FROM FOOD_SCHEDULE WHERE ID=@V_CATEGORY_ID) AND ITEM=(SELECT ITEM FROM stock_available 
 WHERE ITEM=FN_I_ITEM_NAME AND FOOD_TYPE=(SELECT FOOD_TYPE FROM FOOD_SCHEDULE WHERE ID=@V_CATEGORY_ID) ) );	
	
	SET @AVILABLE_QUANTITY=QUANTY_LEFT -ITEM_QUANTITY;
	IF @AVILABLE_QUANTITY >=0 THEN
		SET QUANTITY_AVILABLE_FLAG=TRUE;
	ELSE
		SET QUANTITY_AVILABLE_FLAG=FALSE;
	END IF;
return QUANTITY_AVILABLE_FLAG;
END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
