/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.5.22 : Database - resturant
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`resturant` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `resturant`;

/* Function  structure for function  `ITEM_VALIDATIONS_TEST` */

/*!50003 DROP FUNCTION IF EXISTS `ITEM_VALIDATIONS_TEST` */;
DELIMITER $$

/*!50003 CREATE DEFINER=`root`@`localhost` FUNCTION `ITEM_VALIDATIONS_TEST`(I_ITEM_NAMES CHAR(50)) RETURNS tinyint(1)
BEGIN
DECLARE VALID_ITEM BOOLEAN;
DECLARE CATEGORY_ID INT;
DECLARE ITEM_OBTAINED TEXT;		
DECLARE ITEM_LENGTH_OBTAINED INT;
DECLARE FINAL_ITEM TEXT;
 ITERATOR :
         LOOP    
          IF LENGTH(TRIM(I_ITEM_NAMES)) = 0 OR I_ITEM_NAMES IS NULL THEN
              LEAVE ITERATOR;
              END IF;              	              
              	
		 SET ITEM_OBTAINED = SUBSTRING_INDEX(I_ITEM_NAMES,',',1);
                 SET ITEM_LENGTH_OBTAINED = LENGTH(ITEM_OBTAINED);
                 SET FINAL_ITEM = TRIM(ITEM_OBTAINED); 
                 SET @LENTH=(SELECT LENGTH(I_ITEM_NAMES) - LENGTH(REPLACE(I_ITEM_NAMES, ',' ,''))+1);      
          
                         
IF EXISTS( SELECT ITEM FROM food_items WHERE ITEM=FINAL_ITEM) THEN
	
	SET VALID_ITEM=TRUE;
ELSE
	SET VALID_ITEM=FALSE;
END IF;
IF VALID_ITEM THEN
	  SET I_ITEM_NAMES = INSERT(I_ITEM_NAMES,1,ITEM_LENGTH_OBTAINED + 1,'');   
ELSE
	SET VALID_ITEM=FALSE;
LEAVE ITERATOR;
END IF;              
END LOOP;
RETURN VALID_ITEM;
END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
