/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.5.22 : Database - resturant
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`resturant` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `resturant`;

/* Procedure structure for procedure `CANCEL_ORDER` */

/*!50003 DROP PROCEDURE IF EXISTS  `CANCEL_ORDER` */;

DELIMITER $$

/*!50003 CREATE DEFINER=`root`@`localhost` PROCEDURE `CANCEL_ORDER`(IN PROC_IN_CANCEL_ITEM_NAME CHAR(20),IN PROC_IN_CANCEL_ORDER_NO INT,IN PROC_IN_CANCEL_QUANTITY INT)
BEGIN
DECLARE QUANTITY_IN_ORDERED_DETAILS INT;
IF EXISTS(SELECT ORDER_ID FROM order_details WHERE ORDER_ID= PROC_IN_CANCEL_ORDER_NO) THEN
IF EXISTS(SELECT DISTINCT ITEM_ID FROM order_details WHERE ITEM_ID=(SELECT ID FROM food_items WHERE ITEM=PROC_IN_CANCEL_ITEM_NAME)) THEN
	SET QUANTITY_IN_ORDERED_DETAILS = (SELECT QUANTITY FROM order_details WHERE ITEM_ID=
								(SELECT ID FROM food_items WHERE ITEM=PROC_IN_CANCEL_ITEM_NAME) 
						AND ORDER_ID=PROC_IN_CANCEL_ORDER_NO and status='ORDERED'
						);							
	IF PROC_IN_CANCEL_QUANTITY = QUANTITY_IN_ORDERED_DETAILS THEN
							
		UPDATE order_details SET STATUS='CANCELLED' WHERE ITEM_ID=(SELECT ID FROM food_items WHERE ITEM=PROC_IN_CANCEL_ITEM_NAME) AND
							QUANTITY=PROC_IN_CANCEL_QUANTITY AND ORDER_ID=PROC_IN_CANCEL_ORDER_NO
							AND STATUS='ORDERED';
		
		 
		ELSEif PROC_IN_CANCEL_QUANTITY > QUANTITY_IN_ORDERED_DETAILS OR PROC_IN_CANCEL_QUANTITY <= 0 THEN
		
		SELECT 'Invalid Quantity Entered';
		
	ELSEif 	PROC_IN_CANCEL_QUANTITY < QUANTITY_IN_ORDERED_DETAILS then
		
		INSERT INTO order_details (ORDER_ID,ITEM_ID,QUANTITY,STATUS) VALUES 
		(
		PROC_IN_CANCEL_ORDER_NO,
		(SELECT ID FROM food_items WHERE ITEM=PROC_IN_CANCEL_ITEM_NAME),
		PROC_IN_CANCEL_QUANTITY,'CANCELLED'
		 ) ;
	UPDATE ORDER_DETAILS SET QUANTITY=QUANTITY-PROC_IN_CANCEL_QUANTITY  WHERE 
	ORDER_ID=PROC_IN_CANCEL_ORDER_NO AND 
	ITEM_ID=(SELECT ID FROM FOOD_ITEMS WHERE ITEM=PROC_IN_CANCEL_ITEM_NAME)
				
	AND STATUS='ORDERED' ;
	else
	select 'Invalid quantity entered';
			
	END IF;
ELSE
	SELECT ' Please Enter the correct item name';
END IF;
else
	select 'Please enter a valid order id';
end if;
END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
